### ISSUE TITLE
Information about group members

### ISSUE THREAD

**Issue by clin2on3mun** [forLoop94/Javascript_capstone#21]
This group consist of 2 people @clin2on3mun  and @forLoop94 
https://github.com/forLoop94/Javascript_capstone/projects/1

**Comment by Gambit142** [comment]
Hi @clin2on3mun @forLoop94 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Created Kanban board correctly ✔️ 
- Tasks are shared in an even manner ✔️ 
- Each task has a title, description and number of points ✔️
- Each task is assigned to a team member ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
